development:
  adapter: postgresql
  encoding: unicode
  database: habitat_web_postgres_development
  pool: 5
  username: carlgoulding
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: habitat_web_postgres_test
  pool: 5
  username: carlgoulding
  password:
